language: php

cache:
  directories:
  - "$HOME/.composer/cache"

matrix:
  include:
  - php: 7.1
    env: LARAVEL=5.4

script:
- vendor/bin/phpunit -c phpunit.xml tests/

install: composer install --no-interaction